Update license to AGPL
UMSKT/UMSKT pull request #25
Opened 2023-06-16 19:41 UTC by Neo-Desktop

As per contributor quorum on 17/06/2023 - update license to AGPL

This PR also adds known history to files

2023-06-16 20:23 UTC, CONIGUERO approved these changes
Would rebrand to UMSKT, aside from that I approve

2023-06-16 20:23 UTC, thepwrtank18 requested changes
We should change WindowsXPKg to UMSKT, since that's the new name now (and do the same for everything else in the GitHub repo).

2023-06-16 20:32 UTC, thepwrtank18 commented on src/BINK1998.cpp
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:32 UTC, thepwrtank18 commented on src/BINK2002.h
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:33 UTC, thepwrtank18 commented on src/cli.cpp
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:33 UTC, thepwrtank18 commented on src/cli.h
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:33 UTC, thepwrtank18 commented on src/confid.cpp
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:33 UTC, thepwrtank18 commented on src/confid.h
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:33 UTC, thepwrtank18 commented on src/header.h
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:34 UTC, thepwrtank18 commented on src/key.cpp
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:34 UTC, thepwrtank18 commented on src/main.cpp
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 20:34 UTC, thepwrtank18 commented on src/util.cpp
> + * Copyleft (C) 2019-2023 WindowsXPKg Contributors (et.al.)
```suggestion
 * Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
```

2023-06-16 21:57 UTC, WitherOrNot reviewed
Echoing @thepwrtank18, everything looks good except the project name

2023-06-16 22:05 UTC, thepwrtank18 approved these changes
All clear from what I see.

2023-06-16 22:05 UTC, WitherOrNot requested changes

2023-06-16 22:05 UTC, WitherOrNot commented on README.md
> +* [Please see ticket #8 for more information](../../issues/3)
incorrect issue number

2023-06-16 22:05 UTC, WitherOrNot commented on README.md
> +* [Please see ticket #8 for more information](../../issues/3)
should be #8

2023-06-16 22:11 UTC, WitherOrNot approved these changes
All links, badges work, gud2go

2023-06-16 23:47 UTC, CONIGUERO approved these changes

2023-06-16 23:52 UTC, merged

2023-06-16 23:53 UTC, thepwrtank18 commented
![image](https://github.com/UMSKT/UMSKT/assets/57580668/4b4d367f-6f51-4b24-ac4c-438d958db815)
verification that @Endermanch approved it

2023-06-17 06:58 UTC, Endermanch reviewed
👍